# Generated by Django 5.2 on 2025-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='iv',
            field=models.CharField(max_length=256),
        ),
    ]
