from django.urls import path
from .views import signup_view, verify_otp, resendotp, login,logout_view, profile_view, refresh_token,reset_password, reset_password_confirm,send_reset_otp,upload_image, update_username, verify_identity,verify_captcha, get_users,set_csrf_cookie, followUser, reportUser, blockUser, unblockUser, acceptFollowRequest, rejectFollowRequest, create_post, get_posts, toggle_like

urlpatterns = [
    path('signup/', signup_view, name="signup"),
    path('verifyotp/', verify_otp, name="verifyotp"),
    path('resendotp/', resendotp, name="resendotp"),
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('refresh/', refresh_token, name='refresh'),
    path('reset-password/', reset_password, name='reset-password'),
    path('identityverify/', reset_password_confirm, name='identityverify'),
    path('send_reset_otp/', send_reset_otp, name='send_reset_otp'),
    path('upload_image/', upload_image, name='upload_image'),
    path('update_username/', update_username, name='update_username'),
    path('verify_identity/', verify_identity, name='verify_identity'),
    path('verify-captcha/', verify_captcha, name='verify_captcha'),
    path('get_users/', get_users, name='get_users'),
    path('csrf_cookie/', set_csrf_cookie, name='set_csrf_cookie'),
    path('follow/', followUser, name='followUser'),
    path('report/', reportUser, name='reportUser'),
    path('block/', blockUser, name='blockUser'),
    path('unblock/', unblockUser, name='unblockUser'),
    path('accept_follow_request/', acceptFollowRequest, name='acceptFollowRequest'),
    path('reject_follow_request/', rejectFollowRequest, name='rejectFollowRequest'),
    path('create_post/', create_post, name='create_post'),
    path('get_posts/', get_posts, name='create_post'),
    path('toggle_like/', toggle_like, name='toggle_like'),
]
