# Generated by Django 5.2 on 2025-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(default='o5ZYu4oXzEB7M9Va0+0EKA==', max_length=256),
        ),
    ]
