# Generated by Django 5.2 on 2025-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_filemessage_file_type_filemessage_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfilemessage',
            name='file_type',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AddField(
            model_name='groupfilemessage',
            name='filename',
            field=models.CharField(default='tmp.txt', max_length=255),
        ),
    ]
